name: KBuild

on:
  workflow_dispatch:

jobs:
  kb:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clean
      uses: rokibhasansagar/slimhub_actions@main
    - name: Install tools
      run: |
        sudo apt-get update -y &>/dev/null || sudo apt-get update -y &>/dev/null || true
        sudo apt-get upgrade -y &>/dev/null || sudo apt-get upgrade -y &>/dev/null || true
        sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils -y || sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils -y
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%d.%m.%Y')"
    - name: Build
      run: |
        rm -rf setup.sh*
        rm -rf KernelSU*
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
        echo "Applied KernelSU-Next & susfs4ksu"
        export FIREASF_VANILLA=true
        ./kernel_build/build-fireasf.sh "$(pwd)" || exit 1
        export FIREASF_VANILLA=false
        ./kernel_build/build-fireasf.sh "$(pwd)" || exit 1

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Kernels_a53x
        path: kernel_build/FireAsf/${{ steps.date.outputs.date }}/FireAsf*
