name: FireAsf Auto Builds

on:
  workflow_dispatch:

jobs:
  kb:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: '5.10.234-testing' 

    - name: Clean
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install tools
      run: |
        sudo apt-get update -y || sudo apt-get update -y || true
        sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils checkinstall libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev -y || sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils checkinstall libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev -y

    - name: Build python2
      run: |
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar -xvf Python-2.7.18.tgz
        cd Python-2.7.18
        ./configure --enable-optimizations
        make -j$(nproc --all)
        sudo ln -sf ./python /usr/bin/python2


    - name: Get current date
      id: date
      run: echo "date=$(date +'%d.%m.%Y')" >> "$GITHUB_ENV"

    - name: Build
      run: |
        rm -rf setup.sh* KernelSU*
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
        echo "Applied KernelSU-Next & susfs4ksu"
        export WORKFLOW=true
        export FIREASF_VANILLA=true
        ./kernel_build/build-fireasf.sh "$(pwd)" || exit 1
        export FIREASF_VANILLA=false
        ./kernel_build/build-fireasf.sh "$(pwd)" || exit 1

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: FireAsf_a53x
        path: kernel_build/FireAsf/${{ env.date }}/FireAsf*

